// src/components/ThemeSwitcher.tsx
import { dark, toggleDark } from "./Theme";

export const ThemeSwitcher = () => {
  return (
    <button
      type="button"
      bg-transparent
      onClick={toggleDark}
      aria-label={`Switch to ${dark() ? "light" : "dark"} mode`}
    >
      <div i-pixelarticons={dark() ? "moon" : "sun-alt"} />
    </button>
  );
};

export default ThemeSwitcher;

// src/components/solid/ThemeSwitcher.tsx
import { createEffect, createSignal, onMount } from 'solid-js';

export default function ThemeSwitcher() {
  const [dark, setDark] = createSignal(false);

  onMount(() => {
    setDark(localStorage.getItem('theme') === 'dark');

    createEffect(() => {
      document.documentElement.classList.toggle('dark', dark());
      window.localStorage.setItem('theme', dark() ? 'dark' : 'light');
    });
  });

  return (
    <button
      type="button"
      aria-label={`Toggle ${dark() ? 'light' : 'dark'} mode`}
      class="bg-transparent"
      onClick={() => setDark((dark) => !dark)}
    >
      <svg class="i-pixelarticons:sun-alt dark:i-pixelarticons:moon" />
    </button>
  );
}
